# Generated by Django 5.0.6 on 2024-05-24 18:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDepartment',
            fields=[
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('undelivered_orders_count', models.PositiveIntegerField(default=0)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Велосипед'), ('car', 'Автомобиль'), ('scooter', 'Скутер')], max_length=50)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers', to='delivery_api.deliverydepartment')),
            ],
        ),
    ]
