# Generated by Django 5.0.6 on 2024-05-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='external_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deliverydepartment',
            name='external_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
