# Generated by Django 5.0.6 on 2024-05-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_api', '0003_alter_courier_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='external_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deliverydepartment',
            name='external_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
