# Generated by Django 5.0.6 on 2024-05-24 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_api', '0004_alter_courier_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='department',
            field=models.ForeignKey(default='27602ab0c01844ac8507b5072f080a611', on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='delivery_api.deliverydepartment'),
            preserve_default=False,
        ),
    ]
