# Generated by Django 5.0.6 on 2024-05-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_api', '0005_alter_courier_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='start_date',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
