# Generated by Django 5.0.6 on 2024-05-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_api', '0006_alter_courier_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
