# Generated by Django 5.0.6 on 2024-05-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_api', '0007_alter_courier_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='vehicle_type',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
