# Generated by Django 5.0.6 on 2024-05-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_api', '0008_alter_courier_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
